---
title: "Informe"
author: "Nombre de los integrantes: <br>Julian Alejandro Usuga Ortiz<br> Juan Jose Hurtado Alvarez<br> Diego de Oliveira Hitzges<br> Santiago Campos Giraldo<br>"
date: "4/4/2021"
output: html_document
---


<br>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Introducción

Este aplicativo se realiza con la motivacion de realizar un trabajo analitico para llegar a un dato bastante útil como lo es el numero de hijos usando tecnicas de aprendizaje estadistico modernas en datos abiertos proporcionados por el DANE (Departamento Administrativo Nacional de Estadística).

Esta encuesta fue realizada en el 2019 y recoge datos de los servicios de los hogares, composicion de los hogares, entre otros.


## Retos

Como en cualquier problema de datos, estos no estaban inicialmente en un formato que nos pudiera analizarlos con facilidad, el primer reto fue que los encabezados de las columnas no tenian un identificador facil de diferenciar, asi que tuvimos que recurrir varias veces a la documentacion de la encuesta para poder saber con que variables tratabamos.
Otro reto fue unir las bases de datos ya que estas estan separadas, elegir muy bien cuales usar ya que no todas ayudan a estimar correctamente el numero de hijos y podrian dañar nuestro modelo predictivo.

## Materiales

Para nuestro trabajo preditivo usamos las siguientes herramientas
Lenguajes de programación

* Datos publicos de la Encuesta Nacional de Calidad de Vida [Click para visitar sitio](http://microdatos.dane.gov.co/index.php/catalog/678/data_dictionary)
* Lenguajes de programacion
    + R
    + Python
* Paquete para la manipulacion de datos
    + Tidyverse
* Paquete Shiny para aplicaciones web
* Paquete de modelos predictivos
    + Keras

Tambien usamos nuestros modelos ... 

## Metodos 

Primeramente se seleccionaron las variables a anlaizar y se abicaron en un archivo .csv, luego se ese copió parte de los datos en "data2.txt". Se usó "open(data2.txt, r)" en el programa de la red neuronal "neural_net.py" para accesar los datos transformandolos en una lista de listas usando "split". Cada lista interior es la una línea de los datos de la tabla de Excel y sus elementos son las columnas de esta línea. Se cambia la expresión "NA" para el valor de zero (0), de modo que se manejen una variables completamente numéricas. Posteriormente se transforma la lista de listas en un Array (o sea, en una matriz) en cual cada linea es una instancia de hogar y se mezclan estas lineas para que la secuencia no sea siempre la misma. Se escojieron las líneas 2,3,4,5,8,9,10 para crear X_data y se transpone, entonces X_data es una matriz de dimension 7xm, en cual cada columna es una instancia de hogar. se estandariza X para tener todo en una escala común. Para crear las predictoras "Y" se escojió la línea 7 del Array hecho anteriormente para crear Y_data y de mismo modo que con las X se transpone, por lo tanto, Y_data se vuelve una matriz de dimensión 1xm en cual los elementos son los numeros de hijos de cada hogar y finalmente se estandariza Y.

#####Red Neuronal

La red neuronal tiene un hidden layer con 70 hidden units, con función de activación Leaky Relu, el output-layer tiene la dimensión 1 y no hay una función de activación, la cost-function es el MSE y la red se entrenó usando gradient descent, para testear la red se usó k-fold crossvalidation, para lo que se obtuvó un MSE de más o menos 0.25, o sea un RMSE de 0.5 y una accuracy de casi 74%, y bajo estos resultados, se dio por convincente el rendimiento de la red neuronal.
Para evaluar un nuevo hogar, su vetor de atributos es estandardizado y despues pasa toda la red neuronal (usando los parametros que se obtuvieron durante el entrenamiento) para obtener una estimación "y_hat" y este "y_hat" se destandariza y finalmente se redondeado para obtener la predicción.

## Resultado

El resultado de nuestro trabajo se puede evidenciar en el aplicativo, nuestro modelo tiene un error de __ <!--------- FALTA AQUI ---------> lo cual significa que para de acuerdo a los parametros entrados por el usuario, este tiene ....<!--------- FALTA AQUI --------->


## Conclusiones
<!--------- FALTA AQUI --------->
## Bibliografia

https://www.elheraldo.co/colombia/en-ultimos-48-anos-colombianas-pasaron-de-tener-siete-hijos-dos-310604

https://www.elespectador.com/noticias/salud/en-colombia-las-mujeres-tienen-menos-hijos-y-los-hogares-de-solteros-aumentaron/
<!--------- FALTA AQUI --------->
