---
title: "EnsayoKnn"
author: "Juan Jose Hurtado Alvarez"
date: "22/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
```


```{r}
datos <- read.csv("datos.csv")
```

```{r}
head(datos)
```


```{r}
datos <- datos %>%
  mutate_if(is.character, as.factor)
```

```{r}
datos= datos [, c(1,2,3,4,5,6,7,9,10,11,8)]
```

```{r}
head(datos)
```
X1= directorio
X2= p6020
X3= p6040
X4= p5502
X5= p6071
X6= P5667
X6= cant_personas_hogar
X7= i_hogar
X8= p5010
Y= hijos

```{r}
colnames(datos) <- c("X", "X1", "X2","X3", "X4","X5", "X6","X7","X8", "X9", "Y")
```

```{r}
head(datos)
```

```{r}
datos_sel <- subset(datos, select= c('X2','X3','X4','X5','X6','X7','X8','Y'))
```

```{r}
head(datos_sel)
```

```{r}
any(is.na(datos_sel$X8))
```



```{r}
library(caret)
set.seed(2019092)
ctrl<-trainControl(method = "LGOCV",p=0.75,number = 20)
modelo_entrenamiento<-train(Y ~ X2+X3+X4+X6+X7+X8,
             data       = datos_sel,
             method     = "knn",
             preProcess = c("center","scale"),
             tuneGrid   = expand.grid(k = 1:30),
             trControl  = ctrl,
             metric     = "RMSE")
```

```{r}
print(modelo_entrenamiento)
```
